---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydply
spec:
  replicas: 3
  selector:
   matchLabels: 
     app: swiggy
  template:
    meatadata:
       Labels:
         app: swiggy
    spec:
      cotainers:
        - name: mycont
          image: rohith03ar/myrepo:love
          ports:
            - containetrPorts: 80

